name: ❓ Question
description: Ask a question about LineraDB
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!
  
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help?